# Generated by Django 3.0.7 on 2021-12-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_is_agreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='doctor',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
