# Generated by Django 3.0.7 on 2021-12-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pill_name',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
