# Generated by Django 3.0.7 on 2021-12-09 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211208_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='storage',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='reg_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 9, 19, 51, 37, 202844)),
            preserve_default=False,
        ),
    ]
