# Generated by Django 3.0.7 on 2021-12-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211209_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='count_by_recipe',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='patient_id',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
    ]
