# Generated by Django 3.0.7 on 2021-12-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211216_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='counter',
            new_name='count',
        ),
    ]
